server:
  port: 8083

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/weather_analytic_db
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: weather_events
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: analytic-consumer-group
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
