server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
