server:
  port: 8085

app:
  jwt:
    secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

spring:
  application:
    name: DATA-NOTIFIER-SERVICE
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/notify_db
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: weather_events
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notifier-consumer-group
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
