server:
  port: 8082

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update